name: Build App
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python scraper.py
      - run: |
          git config user.name "AutoBot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Update Zawamil" || echo "No changes"
          git push
